server {
    listen 80;
    listen [::]:80;
    server_name app.baotienweb.cloud;

    root /var/www/app.baotienweb.cloud;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location /_expo {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
