// Construction Design Permission System
export interface ConstructionUser {
  id: string;
  email: string;
  phone: string;
  password_hash: string;
  full_name: string;
  role: string;
  status: 'active' | 'inactive' | 'suspended';
  created_at: string;
  updated_at: string;
}

export interface ConstructionRole {
  roleid: string;
  name: string;
  permissions: string[]; // Array of permission strings
}

// Định nghĩa các quyền cụ thể trong hệ thống xây dựng
export const CONSTRUCTION_PERMISSIONS = {
  // System Management (Admin cao nhất)
  SYSTEM_ADMIN: 'system.admin',
  SYSTEM_CONFIG: 'system.config',
  SYSTEM_BACKUP: 'system.backup',
  
  // User Management
  USER_VIEW: 'user.view',
  USER_CREATE: 'user.create',
  USER_EDIT: 'user.edit',
  USER_DELETE: 'user.delete',
  USER_ASSIGN_ROLE: 'user.assign_role',
  
  // Role & Permission Management
  ROLE_VIEW: 'role.view',
  ROLE_CREATE: 'role.create',
  ROLE_EDIT: 'role.edit',
  ROLE_DELETE: 'role.delete',
  PERMISSION_ASSIGN: 'permission.assign',
  
  // Project Management
  PROJECT_VIEW: 'project.view',
  PROJECT_CREATE: 'project.create',
  PROJECT_EDIT: 'project.edit',
  PROJECT_DELETE: 'project.delete',
  PROJECT_ASSIGN: 'project.assign',
  
  // Design Management
  DESIGN_VIEW: 'design.view',
  DESIGN_CREATE: 'design.create',
  DESIGN_EDIT: 'design.edit',
  DESIGN_DELETE: 'design.delete',
  DESIGN_APPROVE: 'design.approve',
  DESIGN_EXPORT: 'design.export',
  
  // Construction Management
  CONSTRUCTION_VIEW: 'construction.view',
  CONSTRUCTION_CREATE: 'construction.create',
  CONSTRUCTION_EDIT: 'construction.edit',
  CONSTRUCTION_SCHEDULE: 'construction.schedule',
  CONSTRUCTION_ASSIGN_WORKER: 'construction.assign_worker',
  
  // Quality Control
  QUALITY_VIEW: 'quality.view',
  QUALITY_INSPECT: 'quality.inspect',
  QUALITY_APPROVE: 'quality.approve',
  QUALITY_REPORT: 'quality.report',
  
  // Finance Management
  FINANCE_VIEW: 'finance.view',
  FINANCE_CREATE_QUOTE: 'finance.create_quote',
  FINANCE_APPROVE_PAYMENT: 'finance.approve_payment',
  FINANCE_VIEW_REPORT: 'finance.view_report',
  
  // Customer Management
  CUSTOMER_VIEW: 'customer.view',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_EDIT: 'customer.edit',
  CUSTOMER_COMMUNICATE: 'customer.communicate',
  
  // Report Access
  REPORT_VIEW_ALL: 'report.view_all',
  REPORT_EXPORT: 'report.export',
  REPORT_ANALYTICS: 'report.analytics',
} as const;

// Định nghĩa các nhóm người dùng
export const CONSTRUCTION_ROLES = {
  ADMIN: 'admin',                    // Admin cao nhất
  MANAGER: 'manager',                // Quản lý
  CUSTOMER_SERVICE: 'customer_service',  // CSKH
  QUALITY_CONSULTANT: 'quality_consultant', // Tư vấn chất lượng
  ARCHITECT: 'architect',            // Kiến trúc sư
  CONSTRUCTION_COMPANY: 'construction_company', // Công ty xây dựng
  CONTRACTOR: 'contractor',          // Nhà thầu
  WORKER: 'worker',                  // Thợ xây
  CUSTOMER: 'customer',              // Khách hàng (quan trọng nhất)
} as const;

// Mapping role với permissions mặc định
export const CONSTRUCTION_ROLE_PERMISSIONS: Record<string, string[]> = {
  [CONSTRUCTION_ROLES.ADMIN]: [
    // Admin có tất cả quyền
    CONSTRUCTION_PERMISSIONS.SYSTEM_ADMIN,
    CONSTRUCTION_PERMISSIONS.SYSTEM_CONFIG,
    CONSTRUCTION_PERMISSIONS.SYSTEM_BACKUP,
    CONSTRUCTION_PERMISSIONS.USER_VIEW,
    CONSTRUCTION_PERMISSIONS.USER_CREATE,
    CONSTRUCTION_PERMISSIONS.USER_EDIT,
    CONSTRUCTION_PERMISSIONS.USER_DELETE,
    CONSTRUCTION_PERMISSIONS.USER_ASSIGN_ROLE,
    CONSTRUCTION_PERMISSIONS.ROLE_VIEW,
    CONSTRUCTION_PERMISSIONS.ROLE_CREATE,
    CONSTRUCTION_PERMISSIONS.ROLE_EDIT,
    CONSTRUCTION_PERMISSIONS.ROLE_DELETE,
    CONSTRUCTION_PERMISSIONS.PERMISSION_ASSIGN,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.PROJECT_CREATE,
    CONSTRUCTION_PERMISSIONS.PROJECT_EDIT,
    CONSTRUCTION_PERMISSIONS.PROJECT_DELETE,
    CONSTRUCTION_PERMISSIONS.PROJECT_ASSIGN,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_CREATE,
    CONSTRUCTION_PERMISSIONS.DESIGN_EDIT,
    CONSTRUCTION_PERMISSIONS.DESIGN_DELETE,
    CONSTRUCTION_PERMISSIONS.DESIGN_APPROVE,
    CONSTRUCTION_PERMISSIONS.DESIGN_EXPORT,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_CREATE,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_EDIT,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_SCHEDULE,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_ASSIGN_WORKER,
    CONSTRUCTION_PERMISSIONS.QUALITY_VIEW,
    CONSTRUCTION_PERMISSIONS.QUALITY_INSPECT,
    CONSTRUCTION_PERMISSIONS.QUALITY_APPROVE,
    CONSTRUCTION_PERMISSIONS.QUALITY_REPORT,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW,
    CONSTRUCTION_PERMISSIONS.FINANCE_CREATE_QUOTE,
    CONSTRUCTION_PERMISSIONS.FINANCE_APPROVE_PAYMENT,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW_REPORT,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_VIEW,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_CREATE,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_EDIT,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_COMMUNICATE,
    CONSTRUCTION_PERMISSIONS.REPORT_VIEW_ALL,
    CONSTRUCTION_PERMISSIONS.REPORT_EXPORT,
    CONSTRUCTION_PERMISSIONS.REPORT_ANALYTICS,
  ],
  
  [CONSTRUCTION_ROLES.MANAGER]: [
    // Quản lý
    CONSTRUCTION_PERMISSIONS.USER_VIEW,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.PROJECT_CREATE,
    CONSTRUCTION_PERMISSIONS.PROJECT_EDIT,
    CONSTRUCTION_PERMISSIONS.PROJECT_ASSIGN,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_APPROVE,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_SCHEDULE,
    CONSTRUCTION_PERMISSIONS.QUALITY_VIEW,
    CONSTRUCTION_PERMISSIONS.QUALITY_REPORT,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW_REPORT,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_VIEW,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_EDIT,
    CONSTRUCTION_PERMISSIONS.REPORT_VIEW_ALL,
    CONSTRUCTION_PERMISSIONS.REPORT_EXPORT,
  ],
  
  [CONSTRUCTION_ROLES.CUSTOMER_SERVICE]: [
    // Chăm sóc khách hàng
    CONSTRUCTION_PERMISSIONS.CUSTOMER_VIEW,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_CREATE,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_EDIT,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_COMMUNICATE,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.FINANCE_CREATE_QUOTE,
  ],
  
  [CONSTRUCTION_ROLES.QUALITY_CONSULTANT]: [
    // Tư vấn chất lượng
    CONSTRUCTION_PERMISSIONS.QUALITY_VIEW,
    CONSTRUCTION_PERMISSIONS.QUALITY_INSPECT,
    CONSTRUCTION_PERMISSIONS.QUALITY_APPROVE,
    CONSTRUCTION_PERMISSIONS.QUALITY_REPORT,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_COMMUNICATE,
  ],
  
  [CONSTRUCTION_ROLES.ARCHITECT]: [
    // Kiến trúc sư
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_CREATE,
    CONSTRUCTION_PERMISSIONS.DESIGN_EDIT,
    CONSTRUCTION_PERMISSIONS.DESIGN_EXPORT,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.PROJECT_EDIT,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_VIEW,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_COMMUNICATE,
  ],
  
  [CONSTRUCTION_ROLES.CONSTRUCTION_COMPANY]: [
    // Công ty xây dựng
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_CREATE,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_EDIT,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_SCHEDULE,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_ASSIGN_WORKER,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.QUALITY_VIEW,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW,
  ],
  
  [CONSTRUCTION_ROLES.CONTRACTOR]: [
    // Nhà thầu
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_EDIT,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.QUALITY_VIEW,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW,
  ],
  
  [CONSTRUCTION_ROLES.WORKER]: [
    // Thợ xây
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
  ],
  
  [CONSTRUCTION_ROLES.CUSTOMER]: [
    // Khách hàng (quan trọng nhất)
    CONSTRUCTION_PERMISSIONS.PROJECT_VIEW,
    CONSTRUCTION_PERMISSIONS.DESIGN_VIEW,
    CONSTRUCTION_PERMISSIONS.CONSTRUCTION_VIEW,
    CONSTRUCTION_PERMISSIONS.QUALITY_VIEW,
    CONSTRUCTION_PERMISSIONS.FINANCE_VIEW,
    CONSTRUCTION_PERMISSIONS.CUSTOMER_COMMUNICATE,
  ],
};

// Helper functions
export const hasPermission = (userPermissions: string[], requiredPermission: string): boolean => {
  return userPermissions.includes(requiredPermission) || userPermissions.includes(CONSTRUCTION_PERMISSIONS.SYSTEM_ADMIN);
};

export const hasAnyPermission = (userPermissions: string[], requiredPermissions: string[]): boolean => {
  return requiredPermissions.some(permission => hasPermission(userPermissions, permission));
};

export const getRolePermissions = (role: string): string[] => {
  return CONSTRUCTION_ROLE_PERMISSIONS[role] || [];
};

// Interface cho AuthContext mở rộng
export interface ConstructionAuthContextType {
  user: ConstructionUser | null;
  role: ConstructionRole | null;
  permissions: string[];
  signIn: (email: string, password: string) => Promise<void>;
  signOut: () => Promise<void>;
  hasPermission: (permission: string) => boolean;
  hasAnyPermission: (permissions: string[]) => boolean;
  hasRole: (role: string) => boolean;
  loading: boolean;
}
