// AUTO-GENERATED by scripts/generate-video-manifest.cjs
// Do not edit manually. Re-run the script after adding/removing videos.
// Note: Files larger than 15MB are skipped. Override with env VIDEOS_MAX_MB.
import type { VideoItem } from './videos';

export const GENERATED_VIDEOS: VideoItem[] = [
  { id: 'local:reels:carbon', title: 'CARBON', url: require('../assets/videos/CARBON.mp4'), category: 'reels', type: 'vod' },
  { id: 'local:reels:vid20250921094034-1', title: 'VID20250921094034 1', url: require('../assets/videos/VID20250921094034_1.mp4'), category: 'reels', type: 'vod' }
];
