// AUTO-GENERATED by scripts/generate-video-manifest.cjs
// Do not edit manually. Re-run the script after adding/removing videos.
// Note: Files larger than 15MB are skipped. Override with env VIDEOS_MAX_MB.
import type { VideoItem } from './videos';

export const GENERATED_VIDEOS: VideoItem[] = [
  // No local videos (files removed or too large)
];

